import { useEffect } from "react";

import { useDispatch } from "react-redux";

import Head from "next/head";

import styled from "@emotion/styled";

import Header from "../componentes/Header";
import Banner from "../componentes/Banner";
import Productos from "../componentes/Productos";

import { cargarProductosDesdeLocalStorage } from "../redux/cestaSlice";

// -----------------------------------------------
// -----------------------------------------------
// - Componente para mostrar la página de inicio -
// -----------------------------------------------
// -----------------------------------------------
export default function Home({ productos }) {
  const dispatch = useDispatch();

  // ------------------------------------------------------------------------------
  // - UseEffect para obtener los objetos de la cesta almacenados en localStorage -
  // - Estan almacenados en localStorage para no perder su valor                  -
  // - al hacer un refresh de la página (F5)                                      -
  // ------------------------------------------------------------------------------
  useEffect(() => {
    const productosLocalStorage = JSON.parse(localStorage.getItem("productos"));
    if (productosLocalStorage && productosLocalStorage.length > 0) {
      dispatch(
        cargarProductosDesdeLocalStorage(
          JSON.parse(localStorage.getItem("productos"))
        )
      );
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // -------
  // - JSX -
  // -------
  return (
    <Contenedor>
      <Head>
        <title>Galizon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Principal>
        <Banner />
        <Productos productos={productos} />
      </Principal>
    </Contenedor>
  );
}

// ------------------------------------------------------------------
// - Función para obtener los objetos desde la API fakestoreapi.com -
// ------------------------------------------------------------------
// export const getServerSideProps = async (contexto) => {
//   const productos = await fetch("https://fakestoreapi.com/products").then(
//     (res) => res.json()
//   );

//   return {
//     props: {
//       productos,
//     },
//   };
// };

// ------------------------------------------------------------------
// - Función para obtener los objetos desde la API fakestoreapi.com -
// ------------------------------------------------------------------
export const getStaticProps = async (contexto) => {
  const productos = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );

  return {
    props: {
      productos,
    },
  };
};

// ---------------------
// - Styled Components -
// ---------------------
const Contenedor = styled.div`
  background: #eaeded;
`;

const Principal = styled.main`
  max-width: 1536px;
  margin: 0 auto;
  padding: 1rem;
`;
